<?php
/**
 * PricingSummary
 *
 * PHP version 5
 *
 * @category Class
 * @package  EBay\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.16.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace EBay\Inventory\Model;

use ArrayAccess;
use EBay\Inventory\ObjectSerializer;

/**
 * PricingSummary Class Doc Comment
 *
 * @category Class
 * @description This type is used to specify the listing price for the product and settings for the Minimum Advertised Price and Strikethrough Pricing features. The &lt;strong&gt;price&lt;/strong&gt; field must be supplied before an offer is published, but a seller may create an offer without supplying a price initially. The Minimum Advertised Price feature is only available on the US site. Strikethrough Pricing is available on the US, eBay Motors, UK, Germany, Canada (English and French), France, Italy, and Spain sites.
 * @package  EBay\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PricingSummary implements ModelInterface, ArrayAccess
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'PricingSummary';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerTypes
        = [
            'auctionReservePrice'            => Amount::class,
            'auctionStartPrice'              => Amount::class,
            'minimumAdvertisedPrice'         => Amount::class,
            'originallySoldForRetailPriceOn' => 'string',
            'originalRetailPrice'            => Amount::class,
            'price'                          => Amount::class,
            'pricingVisibility'              => 'string',
        ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerFormats
        = [
            'auctionReservePrice'            => null,
            'auctionStartPrice'              => null,
            'minimumAdvertisedPrice'         => null,
            'originallySoldForRetailPriceOn' => null,
            'originalRetailPrice'            => null,
            'price'                          => null,
            'pricingVisibility'              => null,
        ];
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap
        = [
            'auctionReservePrice'            => 'auctionReservePrice',
            'auctionStartPrice'              => 'auctionStartPrice',
            'minimumAdvertisedPrice'         => 'minimumAdvertisedPrice',
            'originallySoldForRetailPriceOn' => 'originallySoldForRetailPriceOn',
            'originalRetailPrice'            => 'originalRetailPrice',
            'price'                          => 'price',
            'pricingVisibility'              => 'pricingVisibility',
        ];
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters
        = [
            'auctionReservePrice'            => 'setAuctionReservePrice',
            'auctionStartPrice'              => 'setAuctionStartPrice',
            'minimumAdvertisedPrice'         => 'setMinimumAdvertisedPrice',
            'originallySoldForRetailPriceOn' => 'setOriginallySoldForRetailPriceOn',
            'originalRetailPrice'            => 'setOriginalRetailPrice',
            'price'                          => 'setPrice',
            'pricingVisibility'              => 'setPricingVisibility',
        ];
    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters
        = [
            'auctionReservePrice'            => 'getAuctionReservePrice',
            'auctionStartPrice'              => 'getAuctionStartPrice',
            'minimumAdvertisedPrice'         => 'getMinimumAdvertisedPrice',
            'originallySoldForRetailPriceOn' => 'getOriginallySoldForRetailPriceOn',
            'originalRetailPrice'            => 'getOriginalRetailPrice',
            'price'                          => 'getPrice',
            'pricingVisibility'              => 'getPricingVisibility',
        ];
    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]  $data  Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['auctionReservePrice'] = $data['auctionReservePrice'] ?? null;
        $this->container['auctionStartPrice'] = $data['auctionStartPrice'] ?? null;
        $this->container['minimumAdvertisedPrice'] = $data['minimumAdvertisedPrice'] ?? null;
        $this->container['originallySoldForRetailPriceOn'] = $data['originallySoldForRetailPriceOn'] ?? null;
        $this->container['originalRetailPrice'] = $data['originalRetailPrice'] ?? null;
        $this->container['price'] = $data['price'] ?? null;
        $this->container['pricingVisibility'] = $data['pricingVisibility'] ?? null;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Gets auctionReservePrice
     *
     * @return Amount
     */
    public function getAuctionReservePrice()
    {
        return $this->container['auctionReservePrice'];
    }

    /**
     * Sets auctionReservePrice
     *
     * @param  Amount  $auctionReservePrice  auctionReservePrice
     *
     * @return $this
     */
    public function setAuctionReservePrice($auctionReservePrice)
    {
        $this->container['auctionReservePrice'] = $auctionReservePrice;

        return $this;
    }

    /**
     * Gets auctionStartPrice
     *
     * @return Amount
     */
    public function getAuctionStartPrice()
    {
        return $this->container['auctionStartPrice'];
    }

    /**
     * Sets auctionStartPrice
     *
     * @param  Amount  $auctionStartPrice  auctionStartPrice
     *
     * @return $this
     */
    public function setAuctionStartPrice($auctionStartPrice)
    {
        $this->container['auctionStartPrice'] = $auctionStartPrice;

        return $this;
    }

    /**
     * Gets minimumAdvertisedPrice
     *
     * @return Amount
     */
    public function getMinimumAdvertisedPrice()
    {
        return $this->container['minimumAdvertisedPrice'];
    }

    /**
     * Sets minimumAdvertisedPrice
     *
     * @param  Amount  $minimumAdvertisedPrice  minimumAdvertisedPrice
     *
     * @return $this
     */
    public function setMinimumAdvertisedPrice($minimumAdvertisedPrice)
    {
        $this->container['minimumAdvertisedPrice'] = $minimumAdvertisedPrice;

        return $this;
    }

    /**
     * Gets originallySoldForRetailPriceOn
     *
     * @return string
     */
    public function getOriginallySoldForRetailPriceOn()
    {
        return $this->container['originallySoldForRetailPriceOn'];
    }

    /**
     * Sets originallySoldForRetailPriceOn
     *
     * @param  string  $originallySoldForRetailPriceOn  This field is needed if the Strikethrough Pricing (STP) feature will be used in the offer. This field indicates that the product was sold for the price in the <strong>originalRetailPrice</strong> field on an eBay site, or sold for that price by a third-party retailer. When using the <strong>createOffer</strong> or <strong>updateOffer</strong> calls, the seller will pass in a value of <code>ON_EBAY</code> to indicate that the product was sold for the <strong>originalRetailPrice</strong> on an eBay site, or the seller will pass in a value of <code>OFF_EBAY</code> to indicate that the product was sold for the <strong>originalRetailPrice</strong> through a third-party retailer. This field and the <strong>originalRetailPrice</strong> field are only applicable if the seller and listing are eligible to use the Strikethrough Pricing feature, a feature which is limited to the US (core site and Motors), UK, Germany, Canada (English and French versions), France, Italy, and Spain sites.<br/><br/>This field will be returned if set for the offer. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/inventory/types/slr:SoldOnEnum'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setOriginallySoldForRetailPriceOn($originallySoldForRetailPriceOn)
    {
        $this->container['originallySoldForRetailPriceOn'] = $originallySoldForRetailPriceOn;

        return $this;
    }

    /**
     * Gets originalRetailPrice
     *
     * @return Amount
     */
    public function getOriginalRetailPrice()
    {
        return $this->container['originalRetailPrice'];
    }

    /**
     * Sets originalRetailPrice
     *
     * @param  Amount  $originalRetailPrice  originalRetailPrice
     *
     * @return $this
     */
    public function setOriginalRetailPrice($originalRetailPrice)
    {
        $this->container['originalRetailPrice'] = $originalRetailPrice;

        return $this;
    }

    /**
     * Gets price
     *
     * @return Amount
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param  Amount  $price  price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets pricingVisibility
     *
     * @return string
     */
    public function getPricingVisibility()
    {
        return $this->container['pricingVisibility'];
    }

    /**
     * Sets pricingVisibility
     *
     * @param  string  $pricingVisibility  This field is needed if the Minimum Advertised Price (MAP) feature will be used in the offer. This field is only applicable if an eligible US seller is using the Minimum Advertised Price (MAP) feature and a <strong>minimumAdvertisedPrice</strong> has been specified. The value set in this field will determine whether the MAP price is shown to a prospective buyer prior to checkout through a pop-up window accessed from the View Item page, or if the MAP price is not shown until the checkout flow after the buyer has already committed to buying the item. To show the MAP price prior to checkout, the seller will set this value to <code>PRE_CHECKOUT</code>. To show the MAP price after the buyer already commits to buy the item, the seller will set this value to <code>DURING_CHECKOUT</code>. This field will be ignored if the seller and/or the listing is not eligible for the MAP feature.<br/><br/>This field will be returned if set for the offer. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/inventory/types/slr:MinimumAdvertisedPriceHandlingEnum'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setPricingVisibility($pricingVisibility)
    {
        $this->container['pricingVisibility'] = $pricingVisibility;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer  $offset  Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer  $offset  Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer  $offset  Offset
     * @param  mixed  $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer  $offset  Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
