<?php
/**
 * EbayOfferDetailsWithIdTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EBay\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.16.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EBay\Inventory;

use PHPUnit_Framework_TestCase;

/**
 * EbayOfferDetailsWithIdTest Class Doc Comment
 *
 * @category    Class
 * @description This type provides details of an offer, and is used by the base request payload of the &lt;strong&gt;updateOffer&lt;/strong&gt; call. Every field that is currently set with the unpublished/published offer must also be passed into the &lt;strong&gt;updateOffer&lt;/strong&gt; call, even those fields whose values are not changing. Note that for published offers, a successful &lt;strong&gt;updateOffer&lt;/strong&gt; call will actually update the active eBay listing with whatever changes were made.
 * @package     EBay\Inventory
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EbayOfferDetailsWithIdTest extends PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Test "EbayOfferDetailsWithId"
     */
    public function testEbayOfferDetailsWithId()
    {
    }

    /**
     * Test attribute "availableQuantity"
     */
    public function testPropertyAvailableQuantity()
    {
    }

    /**
     * Test attribute "categoryId"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "charity"
     */
    public function testPropertyCharity()
    {
    }

    /**
     * Test attribute "extendedProducerResponsibility"
     */
    public function testPropertyExtendedProducerResponsibility()
    {
    }

    /**
     * Test attribute "hideBuyerDetails"
     */
    public function testPropertyHideBuyerDetails()
    {
    }

    /**
     * Test attribute "includeCatalogProductDetails"
     */
    public function testPropertyIncludeCatalogProductDetails()
    {
    }

    /**
     * Test attribute "listingDescription"
     */
    public function testPropertyListingDescription()
    {
    }

    /**
     * Test attribute "listingDuration"
     */
    public function testPropertyListingDuration()
    {
    }

    /**
     * Test attribute "listingPolicies"
     */
    public function testPropertyListingPolicies()
    {
    }

    /**
     * Test attribute "listingStartDate"
     */
    public function testPropertyListingStartDate()
    {
    }

    /**
     * Test attribute "lotSize"
     */
    public function testPropertyLotSize()
    {
    }

    /**
     * Test attribute "merchantLocationKey"
     */
    public function testPropertyMerchantLocationKey()
    {
    }

    /**
     * Test attribute "pricingSummary"
     */
    public function testPropertyPricingSummary()
    {
    }

    /**
     * Test attribute "quantityLimitPerBuyer"
     */
    public function testPropertyQuantityLimitPerBuyer()
    {
    }

    /**
     * Test attribute "secondaryCategoryId"
     */
    public function testPropertySecondaryCategoryId()
    {
    }

    /**
     * Test attribute "storeCategoryNames"
     */
    public function testPropertyStoreCategoryNames()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }
}
