<?php
/**
 * InventoryLocationResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EBay\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.16.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EBay\Inventory;

use PHPUnit_Framework_TestCase;

/**
 * InventoryLocationResponseTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the base response of the &lt;strong&gt;getInventoryLocation&lt;/strong&gt; and &lt;strong&gt;getInventoryLocations&lt;/strong&gt; calls. These responses provide details about inventory location(s) defined for the merchant&#x27;s account.
 * @package     EBay\Inventory
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventoryLocationResponseTest extends PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Test "InventoryLocationResponse"
     */
    public function testInventoryLocationResponse()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "locationAdditionalInformation"
     */
    public function testPropertyLocationAdditionalInformation()
    {
    }

    /**
     * Test attribute "locationInstructions"
     */
    public function testPropertyLocationInstructions()
    {
    }

    /**
     * Test attribute "locationTypes"
     */
    public function testPropertyLocationTypes()
    {
    }

    /**
     * Test attribute "locationWebUrl"
     */
    public function testPropertyLocationWebUrl()
    {
    }

    /**
     * Test attribute "merchantLocationKey"
     */
    public function testPropertyMerchantLocationKey()
    {
    }

    /**
     * Test attribute "merchantLocationStatus"
     */
    public function testPropertyMerchantLocationStatus()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "operatingHours"
     */
    public function testPropertyOperatingHours()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "specialHours"
     */
    public function testPropertySpecialHours()
    {
    }
}
