<?php
/**
 * ListingPoliciesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EBay\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.16.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EBay\Inventory;

use PHPUnit_Framework_TestCase;

/**
 * ListingPoliciesTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to identify business policies including payment, return, and fulfillment policies, and also to identify custom policies. These policies are, or will be, associated with the listing. Every published offer must have a payment, return, and fulfillment business policy associated with it. This type is also used to override the shipping costs of one or more shipping service options that are associated with the fulfillment policy, to enable eBay Plus eligibility for a listing, or to enable the Best Offer feature on the listing.
 * @package     EBay\Inventory
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListingPoliciesTest extends PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Test "ListingPolicies"
     */
    public function testListingPolicies()
    {
    }

    /**
     * Test attribute "bestOfferTerms"
     */
    public function testPropertyBestOfferTerms()
    {
    }

    /**
     * Test attribute "eBayPlusIfEligible"
     */
    public function testPropertyEBayPlusIfEligible()
    {
    }

    /**
     * Test attribute "fulfillmentPolicyId"
     */
    public function testPropertyFulfillmentPolicyId()
    {
    }

    /**
     * Test attribute "paymentPolicyId"
     */
    public function testPropertyPaymentPolicyId()
    {
    }

    /**
     * Test attribute "productCompliancePolicyIds"
     */
    public function testPropertyProductCompliancePolicyIds()
    {
    }

    /**
     * Test attribute "returnPolicyId"
     */
    public function testPropertyReturnPolicyId()
    {
    }

    /**
     * Test attribute "shippingCostOverrides"
     */
    public function testPropertyShippingCostOverrides()
    {
    }

    /**
     * Test attribute "takeBackPolicyId"
     */
    public function testPropertyTakeBackPolicyId()
    {
    }
}
