<?php
/**
 * PickupAtLocationAvailabilityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EBay\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.16.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EBay\Inventory;

use PHPUnit_Framework_TestCase;

/**
 * PickupAtLocationAvailabilityTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to specify/indicate the quantity of the inventory item that is available for an In-Store Pickup order at the merchant&#x27;s physical store (specified by the &lt;strong&gt;merchantLocationKey&lt;/strong&gt; field).
 * @package     EBay\Inventory
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PickupAtLocationAvailabilityTest extends PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Test "PickupAtLocationAvailability"
     */
    public function testPickupAtLocationAvailability()
    {
    }

    /**
     * Test attribute "availabilityType"
     */
    public function testPropertyAvailabilityType()
    {
    }

    /**
     * Test attribute "fulfillmentTime"
     */
    public function testPropertyFulfillmentTime()
    {
    }

    /**
     * Test attribute "merchantLocationKey"
     */
    public function testPropertyMerchantLocationKey()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }
}
