<?php

namespace SapientPro\EbayInventorySDK\Models;

use SapientPro\EbayInventorySDK\Enums\MarketplaceEnum;
use SapientPro\EbayInventorySDK\Models\Concerns\FillsModel;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This type is used by the base request of the <strong>WithdrawByInventoryItemGroup</strong> method, which is used to end a multiple-variation listing.
 */
class WithdrawByInventoryItemGroupRequest implements EbayModelInterface
{
    use FillsModel;

    /** This is the unique identifier of the inventory item group. This identifier is automatically generated by eBay once an inventory item group is created. This field is required. */
    #[Assert\Type('string')]
    public ?string $inventoryItemGroupKey = null;

    /** This is the unique identifier of the eBay site for which the offer will be made available. The marketPlaceId enumeration values are found in MarketplaceIdEnum. This field is required. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/inventory/types/slr:MarketplaceEnum'>eBay API documentation</a> */
    #[Assert\Type(MarketplaceEnum::class)]
    public ?MarketplaceEnum $marketplaceId = null;
}
