<?php
/**
 * LocationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EBay\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.16.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EBay\Inventory;

use PHPUnit_Framework_TestCase;

/**
 * LocationApiTest Class Doc Comment
 *
 * @category Class
 * @package  EBay\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LocationApiTest extends PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Test case for createInventoryLocation
     *
     * .
     *
     */
    public function testCreateInventoryLocation()
    {
    }

    /**
     * Test case for deleteInventoryLocation
     *
     * .
     *
     */
    public function testDeleteInventoryLocation()
    {
    }

    /**
     * Test case for disableInventoryLocation
     *
     * .
     *
     */
    public function testDisableInventoryLocation()
    {
    }

    /**
     * Test case for enableInventoryLocation
     *
     * .
     *
     */
    public function testEnableInventoryLocation()
    {
    }

    /**
     * Test case for getInventoryLocation
     *
     * .
     *
     */
    public function testGetInventoryLocation()
    {
    }

    /**
     * Test case for getInventoryLocations
     *
     * .
     *
     */
    public function testGetInventoryLocations()
    {
    }

    /**
     * Test case for updateInventoryLocation
     *
     * .
     *
     */
    public function testUpdateInventoryLocation()
    {
    }
}
